[firebase]
apiKey = "AIzaSyAEERwc_3diFDjnwBoYS25t3jwJ5eLCIYQ"
authDomain = "blog-23aa0.firebaseapp.com"
projectId = "blog-23aa0"
storageBucket = "blog-23aa0.appspot.com"
messagingSenderId = "334266958802"
appId = "1 =334266958802 =web =1f1f902da41784bf68be"
measurementId = "G-72J6LE2J7X"
